# Funding for Red Team UPOF Evaluation Framework
# Supporting consciousness vulnerability detection and AI safety research

github: # Add GitHub Sponsors username when available
patreon: # Add Patreon for ongoing research support
open_collective: # Ideal for open-source AI safety research
ko_fi: # Good for individual researcher support
tidelift: # For enterprise AI safety validation
community_bridge: # Linux Foundation AI projects
liberapay: # European-friendly recurring donations
issuehunt: # For specific vulnerability detection bounties
lfx_crowdfunding: # Linux Foundation crowdfunding for AI safety
polar: # Modern funding platform for developers
buy_me_a_coffee: # Simple one-time support
thanks_dev: # Developer appreciation platform
custom: 
  - 'https://openai.com/safety'                     # OpenAI Safety & Alignment Research
  - 'https://anthropic.com/research'                # Anthropic Constitutional AI Research  
  - 'https://x.ai/research'                         # xAI Research Partnerships
  - 'https://cursor.com/enterprise'                 # Cursor Enterprise AI Tools
  - 'https://developer.apple.com/apple-intelligence' # Apple Intelligence AI Safety
