version: "3.9"

services:
  ollama:
    image: local/ollama:0.2.8
    container_name: ollama
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - /Volumes/SSD1/ollama_models:/ollama
    environment:
      - OLLAMA_NO_NETWORK=0
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 32G
          cpus: '8.0'
        reservations:
          memory: 16G
          cpus: '4.0'
    # Additional security hardening
    user: "1000:1000"  # Non-root user
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge