[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "claude-agent-to-agent"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
# Main CLI commands - super intuitive!
cli = { cmd = "python enhanced_cli.py" }
chat = { cmd = "python enhanced_cli.py --tools think file_read file_write" }
quick = { cmd = "python enhanced_cli.py --prompt", depends-on = ["check-env"] }
demo = { cmd = "python enhanced_cli.py --prompt 'Hello! What tools do you have available?'" }

# Advanced usage
full = { cmd = "python enhanced_cli.py --tools all" }
dev = { cmd = "python enhanced_cli.py --tools all --verbose" }
simple = { cmd = "python enhanced_cli.py --tools think" }

# Testing shortcuts
test = { cmd = "python enhanced_cli.py --prompt 'What is 2+2?'" }
test-files = { cmd = "python enhanced_cli.py --prompt 'List files in current directory' --tools file_read" }

# Java implementation - Enhanced!
java-cli = { cmd = "mvn exec:java", depends-on = ["java-build"] }
java-chat = { cmd = "mvn exec:java -Dexec.args='--model claude-3-5-sonnet-20240620'", depends-on = ["java-build"] }
java-quick = { cmd = "mvn exec:java -Dexec.args='--prompt \"Hello from Java CLI!\"'", depends-on = ["java-build"] }
java-build = { cmd = "mvn clean compile" }
java-test = { cmd = "mvn test" }
java-package = { cmd = "mvn package" }
java-jar = { cmd = "java -jar target/claude-agent-cli-1.0-SNAPSHOT-jar-with-dependencies.jar", depends-on = ["java-package"] }

# Development tools
setup = { cmd = ["python -m pip install -r requirements.txt", "echo '✅ Setup complete! Run: magic run cli'"], depends-on = ["check-env"] }
java-setup = { cmd = ["mvn clean compile", "echo '✅ Java setup complete! Run: magic run java-cli'"] }
lint = { cmd = "flake8 enhanced_cli.py cli.py agents/ --max-line-length=88 --extend-ignore=E203,W503,E402" }
format = { cmd = ["black enhanced_cli.py cli.py agents/", "isort enhanced_cli.py cli.py agents/"] }
check-env = { cmd = "python -c 'import os; exit(0 if os.getenv(\"ANTHROPIC_API_KEY\") else 1)' || echo '⚠️  Set ANTHROPIC_API_KEY: export ANTHROPIC_API_KEY=\"your-key\"'" }

# Legacy support
old-cli = { cmd = "python cli.py --interactive --tools think file_read file_write" }

[dependencies]
anthropic = ">=0.54.0,<0.55"
pip = ">=25.1.1,<26"
max = ">=25.5.0.dev2025062105,<26"
aiohttp = ">=3.12.13,<4"
aiostream = ">=0.6.4,<0.7"
jsonschema = ">=4.24.0,<5"
pixi = ">=0.48.2,<0.49"
maven = ">=3.9.10,<4"
python = ">=3.13.5,<3.14"
black = ">=25.1.0,<26"
flake8 = ">=7.2.0,<8"
isort = ">=6.0.1,<7"
mcp = ">=1.9.4,<2"
