[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "claude-agent-to-agent"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
cli = "python cli.py"
example-simple = "python examples/simple_cli_example.py"
example-mcp = "python examples/mcp_tools_example.py"

[dependencies]
anthropic = ">=0.54.0,<0.55"
pip = ">=25.1.1,<26"
max = ">=25.5.0.dev2025062105,<26"
aiohttp = ">=3.12.13,<4"
aiostream = ">=0.6.4,<0.7"
jsonschema = ">=4.24.0,<5"
pixi = ">=0.48.2,<0.49"
maven = ">=3.9.10,<4"
