[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "claude-agent-to-agent"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
cli = "python cli.py"
example-simple = "python examples/simple_cli_example.py"
example-mcp = "python examples/mcp_tools_example.py"

[dependencies]
anthropic = ">=0.54.0,<0.55"
pip = ">=25.1.1,<26"
max = ">=25.5.0.dev2025061605,<26"
aiohttp = ">=3.8.0,<4"
aiostream = ">=0.4.5,<0.5"
jsonschema = ">=4.22.0,<5"